services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: image_cropper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../backend/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  backend:
    build: ../backend
    env_file: ../backend/.env.docker
    ports:
      - "5001:5001"
    depends_on:
      - database
    volumes:
      - backend_uploads:/app/uploads

  frontend:
    build: .
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  postgres_data:
  backend_uploads: